services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/myapp
    environment:
      DATABASE_URL: "mysql://user:password@db:3306/music_sync"
    depends_on:
      - db

  db:
    image: mysql:8.3
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: music_sync
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql

  spectaql:
    image: nginx:alpine
    volumes:
      - ./docs/spectaql/output:/usr/share/nginx/html
    ports:
      - "8001:80"
