openapi: 3.0.3

info:
  title: Music Sync Backend API
  description: API document
  version: 0.0.0

servers:
  - url: http://{host}:{port}
    description: 開発環境
    variables:
      host:
        default: localhost
      port:
        default: "8003"

paths:
  /v0/users:
    get:
      operationId: getUsers
      summary: 定義例
      description: 定義例
      parameters:
      - name: email
        in: query
        description: メールアドレス
        schema:
          type: string
      - name: name
        in: query
        description: 名前
        schema:
          type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                title: Users
                type: array
                items:
                  title: User
                  type: object
                  properties:
                    id:
                      type: string
                      description: ユーザID
                      example: user_id
                    email:
                      type: string
                      description: メールアドレス
                      example: name@example.com
                    name:
                      type: string
                      description: 名前
                      example: name
